/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_graphbox_free(a: number): void;
export function __wbg_graphbox3d_free(a: number): void;
export function __wbg_get_graphbox3d_x_min(a: number): number;
export function __wbg_set_graphbox3d_x_min(a: number, b: number): void;
export function __wbg_get_graphbox3d_x_max(a: number): number;
export function __wbg_set_graphbox3d_x_max(a: number, b: number): void;
export function __wbg_get_graphbox3d_y_min(a: number): number;
export function __wbg_set_graphbox3d_y_min(a: number, b: number): void;
export function __wbg_get_graphbox3d_y_max(a: number): number;
export function __wbg_set_graphbox3d_y_max(a: number, b: number): void;
export function __wbg_get_graphbox3d_z_min(a: number): number;
export function __wbg_set_graphbox3d_z_min(a: number, b: number): void;
export function __wbg_get_graphbox3d_z_max(a: number): number;
export function __wbg_set_graphbox3d_z_max(a: number, b: number): void;
export function __wbg_get_graphbox_x_min(a: number): number;
export function __wbg_get_graphbox_x_max(a: number): number;
export function __wbg_get_graphbox_y_min(a: number): number;
export function __wbg_get_graphbox_y_max(a: number): number;
export function __wbg_set_graphbox_x_min(a: number, b: number): void;
export function __wbg_set_graphbox_x_max(a: number, b: number): void;
export function __wbg_set_graphbox_y_min(a: number, b: number): void;
export function __wbg_set_graphbox_y_max(a: number, b: number): void;
export function graph_equation_to_float_array(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number): void;
export function graph_equation_to_float_array_3d(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number): void;
export function graph_vector_field(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function graph_vector_field_paths(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
