import { Noto_Sans, Noto_Serif } from "next/font/google";
import "../styles/globals.css";
import "../mathquill-0.10.1/mathquill.css";

import classNames from "classnames";
import Script from "next/script";
import { Providers } from "./providers";

export const metadata = {
  title: "Mr. Pullen's Graphing Calculator",
  // description: "Generated by Next.js",
};

const noto_sans = Noto_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-noto-sans",
  display: "swap",
});

const noto_serif = Noto_Serif({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-noto-serif",
  display: "swap",
});

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    // suppressHydrationWarning is needed for `next-themes` (the dark/light theme
    // toggle library). Note that it only suppresses the warning on this one element,
    // not on its children.
    <html lang="en" suppressHydrationWarning>
      <body
        className={classNames(
          noto_sans.variable,
          noto_serif.variable,
          "font-sans"
        )}
      >
        <Script
          src="https://code.jquery.com/jquery-3.6.1.min.js"
          strategy="beforeInteractive"
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
